#!/usr/bin/env python3
"""Reference parser and validator for System Latin (spec v1.0).

Usage:
    python3 sl_parser.py "Si hostis detectum, tunc defenda."
    python3 sl_parser.py --file messages.txt
    python3 sl_parser.py --tests sl_tests.txt
"""
import json, re, sys, unicodedata, os

HERE = os.path.dirname(os.path.abspath(__file__))
LEX = json.load(open(os.path.join(HERE, 'sl_lexicon.json'), encoding='utf8'))
VERBS, WORDS = LEX['verbs'], LEX['words']

MAX_BYTES = 1024
MAX_TOKENS = 200
MAX_SENTENCES = 16
MAX_CODE_DIGITS = 16

class SLError(Exception):
    def __init__(self, code, msg):
        super().__init__(f'{code}: {msg}')
        self.code, self.msg = code, msg

# ------------------------------------------------------------------ canonical form
def canon(text):
    t = unicodedata.normalize('NFKD', text.lower())
    return ''.join(c for c in t if not unicodedata.combining(c))

# ------------------------------------------------------------------ morphology
PERSONS = [('I', 'o'), ('you', 'as'), ('it', 'at'), ('we', 'amus'), ('you_all', 'atis'), ('they', 'ant')]
INDEX = {}  # surface -> list of analyses

def _add(surface, **an):
    INDEX.setdefault(surface, []).append(an)

def _verb_analyses(stem):
    """All (surface, analysis) pairs generated by the verb paradigm for one stem."""
    ct = stem.endswith('ct')
    out = [(stem + 'a', dict(kind='cmd', verb=stem))]
    for p, e in PERSONS:
        out.append((stem + e, dict(kind='fin', verb=stem, person=p, tense='present')))
        out.append((stem + 'av' + e, dict(kind='fin', verb=stem, person=p, tense='past')))
        out.append((stem + 'abs' + e, dict(kind='fin', verb=stem, person=p, tense='future')))
    out += [(stem + 'atur', dict(kind='pass', verb=stem, number='sg', tense='present')),
            (stem + 'antur', dict(kind='pass', verb=stem, number='pl', tense='present')),
            (stem + 'absatur', dict(kind='pass', verb=stem, number='sg', tense='future')),
            (stem + 'absantur', dict(kind='pass', verb=stem, number='pl', tense='future')),
            (stem + 'are', dict(kind='inf', verb=stem)),
            (stem + 'ans', dict(kind='ing', verb=stem)),
            (stem + 'andum', dict(kind='req', verb=stem)),
            (stem + ('um' if ct else 'atum'), dict(kind='stat', verb=stem)),
            (stem + ('io' if ct else 'atio'), dict(kind='noun', verb=stem, derived='action')),
            (stem + ('or' if ct else 'ator'), dict(kind='noun', verb=stem, derived='agent'))]
    return out

def add_verb(stem, entry):
    VERBS[stem] = entry
    for surface, an in _verb_analyses(stem):
        _add(surface, **an)

def _adverb_of(adj_lemma):
    """Derived manner adverb for a regular -um adjective: strip -um, add -iter."""
    return adj_lemma[:-2] + 'iter' if adj_lemma.endswith('um') else None

def add_word(lemma, entry):
    WORDS[lemma] = entry
    for pos in entry['pos']:
        _add(lemma, kind=pos, lemma=lemma)
    if 'adj' in entry['pos']:
        adv = _adverb_of(lemma)
        if adv:
            _add(adv, kind='adv', lemma=adv, derived_from=lemma)

for _stem in list(VERBS):
    for _surface, _an in _verb_analyses(_stem):
        _add(_surface, **_an)
for _w, _e in WORDS.items():
    for _pos in _e['pos']:
        _add(_w, kind=_pos, lemma=_w)
    if 'adj' in _e['pos']:
        _av = _adverb_of(_w)
        if _av and _av not in INDEX:
            _add(_av, kind='adv', lemma=_av, derived_from=_w)

def snapshot():
    import copy
    return copy.deepcopy((VERBS, WORDS, INDEX))

def restore(snap):
    import copy
    v, w, i = copy.deepcopy(snap)
    VERBS.clear(); VERBS.update(v); WORDS.clear(); WORDS.update(w); INDEX.clear(); INDEX.update(i)

def analyze(tok):
    return INDEX.get(tok, [])

def has(tok, *kinds):
    return any(a['kind'] in kinds for a in analyze(tok))

def ana(tok, kind):
    for a in analyze(tok):
        if a['kind'] == kind:
            return a
    return None

# ------------------------------------------------------------------ tokenizer
def tokenize(text):
    text = canon(text)
    bad = re.findall(r"[^a-z\s.,:?]", text)
    if bad:
        raise SLError('E_CHARSET', f'character not allowed: {sorted(set(bad))}')
    toks = re.findall(r"[a-z]+|[.,:?]", text)
    for t in toks:
        if t.isalpha() and not analyze(t):
            raise SLError('E_UNKNOWN', f'unknown word: {t}')
    return toks

# ------------------------------------------------------------------ numerals
D19 = ['unum', 'duo', 'tria', 'quattuor', 'quinque', 'sex', 'septem', 'octo', 'novem']
PLACE_WORDS = ('decem', 'centum', 'mille', 'milio')

def digit_val(t):
    return 0 if t == 'zero' else D19.index(t) + 1

def is_numtok(t):
    return t in D19 or t == 'zero' or t in PLACE_WORDS or t in ('negatum', 'ordo')

def _tok(toks, k):
    return toks[k] if k < len(toks) else None

def _group(toks, i):
    """Hundreds, tens, ones below 1000. Returns (value or None, next index)."""
    j, val, seen = i, 0, False
    for word, mult in (('centum', 100), ('decem', 10)):
        if _tok(toks, j) == word:
            val += mult; j += 1; seen = True
        elif _tok(toks, j) in D19 and _tok(toks, j + 1) == word:
            if _tok(toks, j) == 'unum':
                raise SLError('E_NUMBER', "'unum' may not precede a place word")
            val += digit_val(toks[j]) * mult; j += 2; seen = True
    t = _tok(toks, j)
    if t in D19 and _tok(toks, j + 1) not in ('centum', 'decem'):
        if _tok(toks, j + 1) in ('mille', 'milio') and t == 'unum':
            raise SLError('E_NUMBER', "'unum' may not precede a place word")
        val += digit_val(t); j += 1; seen = True
    return (val if seen else None), j

def parse_integer(toks, i):
    if _tok(toks, i) == 'zero':
        return 0, i + 1
    total, start = 0, i
    done = set()
    while True:
        g, j = _group(toks, i)
        nxt = _tok(toks, j)
        if nxt in ('mille', 'milio'):
            if nxt in done or (nxt == 'milio' and 'mille' in done):
                raise SLError('E_NUMBER', f"'{nxt}' out of order or repeated")
            done.add(nxt)
            total += (g if g is not None else 1) * (1000000 if nxt == 'milio' else 1000)
            i = j + 1
            continue
        if g is not None:
            total += g; i = j
        break
    return (total if i > start else None), i

def parse_numeral(toks, i):
    """Returns (node, next index) or (None, i)."""
    t = _tok(toks, i)
    if t is None: return None, i
    if t == 'ordo':
        v, j = parse_integer(toks, i + 1)
        if v is None: raise SLError('E_NUMBER', "'ordo' needs a number")
        return {'type': 'ordinal', 'value': v}, j
    neg = False
    if t == 'negatum' and (_tok(toks, i + 1) in D19 or _tok(toks, i + 1) == 'zero' or _tok(toks, i + 1) in PLACE_WORDS):
        neg = True; i += 1; t = toks[i]
    if not (t in D19 or t == 'zero' or t in PLACE_WORDS):
        return None, i
    v, j = parse_integer(toks, i)
    if v is None: return None, i
    value = v
    if _tok(toks, j) == 'punctum':
        k, digs = j + 1, ''
        while _tok(toks, k) in D19 or _tok(toks, k) == 'zero':
            digs += str(digit_val(toks[k])); k += 1
        if not digs: raise SLError('E_NUMBER', "'punctum' needs digits")
        value = float(f'{v}.{digs}'); j = k
    return {'type': 'number', 'value': -value if neg else value}, j

# ------------------------------------------------------------------ parser
class P:
    def __init__(self, toks, mode='stmt'):
        self.t, self.i, self.mode = toks, 0, mode
    def peek(self, k=0):
        return self.t[self.i + k] if self.i + k < len(self.t) else None
    def eof(self): return self.i >= len(self.t)
    def take(self):
        tok = self.t[self.i]; self.i += 1; return tok

QW_SET = {'utrum', 'quis', 'quid', 'quale', 'ubi', 'cur', 'quomodo', 'quantum', 'quando'}

def np_start(tok):
    if tok is None: return False
    if tok in ('negatum', 'ordo'): return True
    if has(tok, 'art'): return True
    return tok in D19 or tok == 'zero' or tok in PLACE_WORDS or tok == 'codex' or has(tok, 'noun', 'pron', 'quant', 'dem')

CLAUSE_HEADS = ('fin', 'cmd', 'pass', 'stat', 'inf', 'ing')

def _digits(p):
    digs = ''
    while p.peek() in D19 or p.peek() == 'zero':
        digs += str(digit_val(p.take()))
    if not digs: raise SLError('E_NUMBER', "'codex' needs digits")
    if len(digs) > MAX_CODE_DIGITS: raise SLError('E_LIMIT', f'code longer than {MAX_CODE_DIGITS} digits')
    return digs

def parse_np(p, attributive=True, allow_bare_number=True):
    node = {'type': 'np'}
    tok = p.peek()
    if tok and has(tok, 'art'):
        node['article'] = p.take(); tok = p.peek()
    if tok and has(tok, 'dem'):
        p.take(); node['demonstrative'] = tok
        nxt = p.peek()
        if not (nxt and np_start(nxt) and not has(nxt, 'dem')):
            return node                     # demonstrative used alone, as a pronoun
        tok = nxt
    if tok == 'codex':
        p.take(); node['head'] = 'codex'; node['digits'] = _digits(p)
        return node
    num, j = parse_numeral(p.t, p.i)
    if num:
        p.i = j; node['quantity'] = num
        if not (p.peek() and has(p.peek(), 'noun', 'pron') and p.peek() != 'codex'):
            if allow_bare_number: return node
            raise SLError('E_SYNTAX', 'number without a noun')
    elif tok and has(tok, 'quant') and not has(tok, 'noun'):
        p.take(); node['quantity'] = tok
        if not (p.peek() and has(p.peek(), 'noun', 'pron')):
            return node
    if not (p.peek() and has(p.peek(), 'noun', 'pron')):
        raise SLError('E_SYNTAX', f"expected a noun, found '{p.peek()}'")
    node['head'] = p.take()
    def adjs():
        out = []
        while p.peek() and has(p.peek(), 'adj') and not has(p.peek(), 'noun'):
            if p.peek() == 'minus' and np_start(p.peek(1)):
                break  # comparator
            out.append(p.take())
        return out
    if attributive:
        node['adj'] = adjs()
    nxt = p.peek()
    if nxt and has(nxt, 'dem') and p.peek(1) and has(p.peek(1), 'noun', 'pron') and not has(p.peek(1), *CLAUSE_HEADS):
        node['dep_demonstrative'] = p.take(); nxt = p.peek()
    if nxt and has(nxt, 'noun', 'pron') and not has(nxt, 'quant') and nxt != 'finis' and not has(nxt, *CLAUSE_HEADS):
        node['dep'] = p.take()
        if node['dep'] == 'codex':
            node['dep_code'] = _digits(p)
        if attributive:
            node['dep_adj'] = adjs()
        nxt = p.peek()
        if nxt and has(nxt, 'noun', 'pron') and not has(nxt, 'quant') and not has(nxt, *CLAUSE_HEADS):
            raise SLError('E_NOUNS', f"too many adjacent nouns at '{nxt}': use a preposition")
    elif 'dep_demonstrative' in node:
        raise SLError('E_SYNTAX', 'demonstrative must be followed by a noun')
    return node

def parse_pp_adv(p):
    out = []
    while p.peek():
        tok = p.peek()
        if has(tok, 'prep') and not (has(tok, 'adv') and not np_start(p.peek(1))):
            prep = p.take()
            if p.peek() in QW_SET:
                out.append({'type': 'pp', 'prep': prep, 'qw': p.take()})
            else:
                out.append({'type': 'pp', 'prep': prep, 'np': parse_np(p)})
        elif has(tok, 'adv'):
            out.append({'type': 'adv', 'word': p.take()})
        else:
            break
    return out

def parse_verb_tail(p, node, an):
    verb = an['verb']
    if p.peek() in QW_SET and p.peek() != 'quando':
        node['embedded'] = parse_question_body(p)
    elif p.peek() and has(p.peek(), 'inf'):
        node['complement'] = parse_clause_full(p)
    elif p.peek() and np_start(p.peek()) and not has(p.peek(), 'adv', 'prep') and p.peek() not in ('donec', 'dum'):
        if VERBS[verb]['valency'] == 'intrans':
            raise SLError('E_VALENCY', f"'{verb}a' is intransitive and takes no object")
        node['object'] = parse_np(p)
    node['mods'] = parse_pp_adv(p)
    return node

def parse_command(p):
    neg = False
    if p.peek() == 'non':
        p.take(); neg = True
    tok = p.peek()
    an = ana(tok, 'cmd') if tok else None
    if not an:
        raise SLError('E_SYNTAX', f"expected a command, found '{tok}'")
    p.take()
    node = {'type': 'command', 'verb': an['verb'], 'form': tok, 'neg': neg}
    parse_verb_tail(p, node, an)
    return node

def parse_pred(p):
    neg = False
    if p.peek() == 'non':
        p.take(); neg = True
    tok = p.peek()
    if tok is None: raise SLError('E_SYNTAX', 'missing predicate')
    for kind in ('stat', 'ing'):
        a = ana(tok, kind)
        if a:
            p.take(); return {'type': 'pred', 'kind': kind, 'verb': a['verb'], 'neg': neg, 'word': tok}
    if has(tok, 'adj') and not has(tok, 'noun'):
        p.take(); return {'type': 'pred', 'kind': 'adj', 'neg': neg, 'word': tok}
    if has(tok, 'adv') or (has(tok, 'prep') and not np_start(p.peek(1))):
        p.take(); return {'type': 'pred', 'kind': 'adv', 'neg': neg, 'word': tok}
    if neg:
        raise SLError('E_NEG', "'non' must come directly before a predicate (verb, status, adjective)")
    return None

def parse_finite_rest(p, subject):
    tok = p.peek()
    neg = False
    if tok == 'non' and p.peek(1) and has(p.peek(1), 'fin', 'pass'):
        p.take(); neg = True; tok = p.peek()
    a = ana(tok, 'fin') or ana(tok, 'pass')
    if not a: return None
    p.take()
    node = {'type': 'finite', 'verb': a['verb'], 'form': tok, 'subject': subject, 'neg': neg, 'kind': a['kind']}
    if a['kind'] == 'fin':
        node['person'] = a['person']; node['tense'] = a['tense']
        parse_verb_tail(p, node, a)
    else:
        node['tense'] = a['tense']; node['mods'] = parse_pp_adv(p)
    return node

def parse_clause(p, cond=False):
    """statement clause: finite, status, comparison, elliptical."""
    tok = p.peek()
    if tok is None: raise SLError('E_SYNTAX', 'empty clause')
    # finite verb without subject
    if has(tok, 'fin', 'pass') or (tok == 'non' and p.peek(1) and has(p.peek(1), 'fin', 'pass')):
        n = parse_finite_rest(p, None)
        if n: return n
    if not cond and (has(tok, 'cmd') or (tok == 'non' and p.peek(1) and has(p.peek(1), 'cmd'))):
        return parse_command(p)
    if np_start(tok):
        subj = parse_np(p)
        nxt = p.peek()
        if nxt is None or nxt in ('donec', 'dum', 'et', 'aut'):
            # a final adjective is the predicate: 'hostis activum' = the enemy is active
            if subj.get('adj') and not subj.get('dep'):
                last = subj['adj'].pop()
                return {'type': 'status', 'subject': subj, 'pred': {'type': 'pred', 'kind': 'adj', 'neg': False, 'word': last}, 'mods': []}
            return {'type': 'nominal', 'np': subj}
        if has(nxt, 'fin', 'pass') or (nxt == 'non' and p.peek(1) and has(p.peek(1), 'fin', 'pass')):
            return parse_finite_rest(p, subj)
        # comparison
        j = 1 if nxt == 'non' else 0
        c = p.peek(j)
        if c in ('aequale', 'maius', 'minus') and p.peek(j + 1) and np_start(p.peek(j + 1)):
            if j: p.take()
            p.take()
            obj = parse_np(p)
            return {'type': 'comparison', 'left': subj, 'op': c, 'neg': bool(j), 'right': obj}
        pr = parse_pred(p)
        if pr:
            return {'type': 'status', 'subject': subj, 'pred': pr, 'mods': parse_pp_adv(p)}
        if has(nxt, 'prep'):
            return {'type': 'status', 'subject': subj, 'pred': None, 'mods': parse_pp_adv(p)}
        _fail(p)
    pr = parse_pred(p)
    if pr:
        return {'type': 'status', 'subject': None, 'pred': pr, 'mods': parse_pp_adv(p)}
    if has(tok, 'prep'):
        return {'type': 'elliptical', 'mods': parse_pp_adv(p)}
    _fail(p)

def _fail(p):
    raise SLError('E_SYNTAX', f"unexpected '{p.peek()}'")

def parse_subordinate(p, node):
    if p.peek() in ('donec', 'dum'):
        conj = p.take()
        node['until' if conj == 'donec' else 'while'] = parse_condition(p)
    return node

def parse_condition(p):
    def atom():
        return parse_clause(p, cond=True)
    def conj():
        parts = [atom()]
        while p.peek() == 'et':
            p.take(); parts.append(atom())
        return parts[0] if len(parts) == 1 else {'type': 'and', 'args': parts}
    parts = [conj()]
    while p.peek() == 'aut':
        p.take(); parts.append(conj())
    if not p.eof() and p.peek() not in (',',):
        raise SLError('E_SYNTAX', f"unexpected '{p.peek()}' in condition")
    return parts[0] if len(parts) == 1 else {'type': 'or', 'args': parts}

def parse_question_body(p):
    node = {'type': 'question'}
    if p.peek() == 'utrum':
        p.take(); node['qw'] = 'utrum'
        node['clause'] = parse_clause_full(p)
        return node
    prep = None
    if has(p.peek(), 'prep') and p.peek(1) in QW_SET:
        prep = p.take()
    qw = p.take(); node['qw'] = qw
    if prep: node['prep'] = prep
    if qw in ('quantum', 'quale') and p.peek() and has(p.peek(), 'noun') and not has(p.peek(), 'fin', 'cmd', 'stat'):
        node['np'] = parse_np(p)
    if not p.eof() and p.peek() != ',':
        node['clause'] = parse_clause_full(p, in_question=True)
    return node

def parse_clause_full(p, in_question=False):
    tok = p.peek()
    if tok and (has(tok, 'inf')):
        a = ana(tok, 'inf'); p.take()
        n = {'type': 'infinitive', 'verb': a['verb']}
        parse_verb_tail(p, n, a)
        return n
    if not in_question:
        return parse_clause(p)
    # question rest: clause or bare np
    if tok and np_start(tok):
        save = p.i
        try:
            return parse_clause(p)
        except SLError:
            p.i = save
    return parse_clause(p)

def split_top(toks, sep):
    out, cur = [], []
    for t in toks:
        if t == sep: out.append(cur); cur = []
        else: cur.append(t)
    out.append(cur)
    return out

def parse_actions(toks):
    acts = []
    for chunk in split_top(toks, ','):
        if not chunk: raise SLError('E_SYNTAX', 'empty action')
        if chunk[0] == 'tunc' and not acts:
            chunk = chunk[1:]
        if chunk and chunk[0] in ('si', 'nisi', 'aliter', 'dum', 'donec', 'quisque'):
            raise SLError('E_NESTED', f"'{chunk[0]}' cannot appear inside a rule branch")
        p = P(chunk)
        n = parse_clause(p)
        parse_subordinate(p, n)
        if not p.eof(): _fail(p)
        acts.append(n)
    return acts

def parse_sentence(toks, term):
    """Returns (node, chain_state)."""
    if not toks: raise SLError('E_SYNTAX', 'empty sentence')
    first = toks[0]
    # question
    is_q = first in QW_SET and not (first == 'quando' and term != '?') \
        or (has(first, 'prep') and len(toks) > 1 and toks[1] in QW_SET and toks[1] != 'quando')
    if term == '?':
        if not is_q: raise SLError('E_QMARK', "'?' used on a sentence with no question word")
        p = P(toks); n = parse_question_body(p)
        if not p.eof(): _fail(p)
        return n
    if is_q and first != 'quando':
        raise SLError('E_QMARK', 'question words require a "?" terminator')
    # rules
    if first in ('si', 'nisi', 'quando', 'dum', 'donec', 'quisque'):
        parts = split_top(toks, ',')
        if len(parts) < 2: raise SLError('E_SYNTAX', f"'{first}' rule needs a comma before the action")
        head, rest = parts[0][1:], toks[len(parts[0]) + 1:]
        if first == 'quisque':
            p = P(head); subj = parse_np(p)
            if not p.eof(): _fail(p)
            cond = subj
        else:
            p = P(head); cond = parse_condition(p)
        return {'type': 'rule', 'kind': first, 'cond': cond, 'actions': parse_actions(rest)}
    if first == 'aliter':
        if len(toks) > 1 and toks[1] == ',':
            return {'type': 'else', 'actions': parse_actions(toks[2:])}
        if len(toks) > 1 and toks[1] == 'si':
            parts = split_top(toks[2:], ',')
            if len(parts) < 2: raise SLError('E_SYNTAX', "'aliter si' rule needs a comma before the action")
            cond = parse_condition(P(parts[0]))
            return {'type': 'else_if', 'cond': cond, 'actions': parse_actions(toks[len(parts[0]) + 3:])}
        raise SLError('E_SYNTAX', "'aliter' must be followed by ',' or 'si'")
    if first == 'finis' and len(toks) == 1:
        return {'type': 'end'}
    if first == 'tunc':
        raise SLError('E_SYNTAX', "'tunc' may only follow the comma of a rule")
    # purpose
    if ':' in toks:
        i = toks.index(':')
        p = P(toks[:i]); head = parse_np(p)
        if not p.eof(): _fail(p)
        rest = toks[i + 1:]
        if rest and has(rest[0], 'inf'):
            q = P(rest); n = parse_clause_full(q)
            parse_subordinate(q, n)
            if not q.eof(): _fail(q)
            return {'type': 'purpose', 'topic': head, 'body': n}
        return {'type': 'purpose', 'topic': head, 'body': parse_actions(rest)}
    if has(first, 'ans') and len(toks) == 1:
        return {'type': 'answer', 'word': first}
    # plain statement / command list
    parts = split_top(toks, ',')
    acts = []
    for chunk in parts:
        p = P(chunk); n = parse_clause(p); parse_subordinate(p, n)
        if not p.eof(): _fail(p)
        acts.append(n)
    return acts[0] if len(acts) == 1 else {'type': 'sequence', 'items': acts}

# ------------------------------------------------------------------ envelope (v1.1)
PRIORITY_LEVELS = ('minimum', 'humile', 'normale', 'altum', 'maximum')

def is_envelope(toks):
    return len(toks) >= 3 and toks[0] == 'nuntius' and toks[1] == 'codex'

def _has_code(np):
    return np.get('head') == 'codex' or 'dep_code' in np

def parse_envelope(toks):
    """nuntius codex <digits> : field { , field }   -> envelope node"""
    p = P(toks); p.take(); p.take()
    ident = _digits(p)
    if p.peek() != ':':
        raise SLError('E_ENVELOPE', "envelope header must be 'nuntius codex <digits>:' followed by fields")
    p.take()
    rest = toks[p.i:]
    env = {'type': 'envelope', 'id': ident, 'priority': 'normale'}
    seen = set()
    if not rest: raise SLError('E_ENVELOPE', 'envelope has no fields')
    for field in split_top(rest, ','):
        if not field: raise SLError('E_ENVELOPE', 'empty envelope field')
        key = field[0]
        if key in seen: raise SLError('E_ENVELOPE', f"duplicate envelope field '{key}'")
        if key in ('ab', 'ad'):
            q = P(field[1:])
            np = parse_np(q)
            if not q.eof(): raise SLError('E_ENVELOPE', f"unexpected '{q.peek()}' in '{key}' field")
            if key == 'ab' and not _has_code(np):
                raise SLError('E_ADDRESS', "sender must carry a code: 'ab agent codex ...'")
            if key == 'ad' and not (_has_code(np) or np.get('quantity') == 'omnia'):
                raise SLError('E_ADDRESS', "receiver must carry a code or be 'omnia' (broadcast)")
            env['from' if key == 'ab' else 'to'] = np
        elif key == 'prioritas':
            if len(field) != 2 or field[1] not in PRIORITY_LEVELS:
                raise SLError('E_PRIORITY', f"priority must be one of {', '.join(PRIORITY_LEVELS)}")
            env['priority'] = field[1]
        elif key == 'responsum':
            if len(field) < 3 or field[1] != 'codex':
                raise SLError('E_ENVELOPE', "'responsum' must be followed by 'codex <digits>'")
            q = P(field[2:]); env['reply_to'] = _digits(q)
            if not q.eof(): raise SLError('E_ENVELOPE', "unexpected word after reply code")
        elif key == 'tempus':
            node, j = parse_numeral(field, 1)
            if not node or j != len(field): raise SLError('E_ENVELOPE', "'tempus' must be followed by a number")
            env['time'] = node['value']
        else:
            raise SLError('E_ENVELOPE', f"unknown envelope field '{key}'")
        seen.add(key)
    for req in ('ab', 'ad'):
        if req not in seen: raise SLError('E_ENVELOPE', f"envelope needs an '{req}' field")
    return env

def parse_message(text, strict=False):
    if len(text.encode('utf-8')) > MAX_BYTES:
        raise SLError('E_LIMIT', f'message longer than {MAX_BYTES} bytes')
    toks = tokenize(text)
    if len(toks) > MAX_TOKENS:
        raise SLError('E_LIMIT', f'message longer than {MAX_TOKENS} tokens')
    if not toks: raise SLError('E_SYNTAX', 'empty message')
    if toks[-1] not in ('.', '?'): raise SLError('E_TERMINATOR', 'message must end with "." or "?"')
    sentences, cur = [], []
    for t in toks:
        if t in ('.', '?'):
            if not cur: raise SLError('E_SYNTAX', 'empty sentence')
            sentences.append((cur, t)); cur = []
        else:
            cur.append(t)
    if len(sentences) > MAX_SENTENCES:
        raise SLError('E_LIMIT', f'more than {MAX_SENTENCES} sentences')
    out, open_chain = [], False
    for k, (toks_, term) in enumerate(sentences):
        if k == 0 and is_envelope(toks_):
            if term != '.': raise SLError('E_ENVELOPE', 'the envelope sentence must end with "."')
            out.append(parse_envelope(toks_)); continue
        if k == 0 and strict:
            raise SLError('E_ENVELOPE', 'strict mode: message must start with an envelope')
        n = parse_sentence(toks_, term)
        kind = n['type'] if isinstance(n, dict) else 'x'
        if kind in ('else', 'else_if'):
            if not open_chain: raise SLError('E_ELSE', "'aliter' has no preceding 'si' or 'nisi' rule")
        if kind == 'rule' and n['kind'] in ('si', 'nisi'):
            open_chain = True
        elif kind == 'else_if':
            open_chain = True
        else:
            open_chain = False
        out.append(n)
    return out

# ------------------------------------------------------------------ canonical text
def canonical_text(text, strict=False):
    """Validate, then return the one canonical spelling of a message (lowercase ASCII,
    single spaces, no space before punctuation, one space after it, no trailing space).
    Signatures are computed over canonical_text(...).encode('utf-8')."""
    parse_message(text, strict)
    out = ''
    for t in tokenize(text):
        if t in '.,:?':
            out += t
        else:
            out += (' ' if out else '') + t
    return out

# ------------------------------------------------------------------ CLI
def check(text, strict=False):
    try:
        return True, parse_message(text, strict)
    except SLError as e:
        return False, {'code': e.code, 'msg': e.msg}

def run_tests(path):
    ok = fail = 0
    for ln, line in enumerate(open(path, encoding='utf8'), 1):
        line = line.rstrip('\n')
        if not line.strip() or line.startswith('#'): continue
        exp, _, text = line.partition(' | ')
        if exp.startswith('NUM '):
            want = float(exp[4:]) if '.' in exp else int(exp[4:])
            try:
                node, j = parse_numeral(tokenize(text), 0)
                got = node['value'] if node else None
                if node and j == len(tokenize(text)) and got == want: ok += 1
                else: fail += 1; print(f'FAIL line {ln}: {text} -> {got}, expected {want}')
            except SLError as e:
                fail += 1; print(f'FAIL line {ln}: {text} raised {e.code}')
            continue
        if exp == 'NUMERR':
            try:
                parse_numeral(tokenize(text), 0)
                fail += 1; print(f'FAIL line {ln}: expected E_NUMBER :: {text}')
            except SLError as e:
                if e.code == 'E_NUMBER': ok += 1
                else: fail += 1; print(f'FAIL line {ln}: got {e.code} :: {text}')
            continue
        strict = exp.endswith('+ENV')
        if strict: exp = exp[:-4]
        good, res = check(text, strict)
        if exp == 'OK':
            if good: ok += 1
            else: fail += 1; print(f'FAIL line {ln}: expected OK, got {res["code"]} ({res["msg"]}) :: {text}')
        else:
            if not good and res['code'] == exp: ok += 1
            else: fail += 1; print(f'FAIL line {ln}: expected {exp}, got {"OK" if good else res["code"]} :: {text}')
    print(f'{ok} passed, {fail} failed')
    return fail == 0

if __name__ == '__main__':
    a = sys.argv[1:]
    if a and a[0] == '--tests':
        sys.exit(0 if run_tests(a[1]) else 1)
    if a and a[0] == '--canonical':
        try:
            print(canonical_text(' '.join(a[1:])))
        except SLError as e:
            print(f'ERR {e}'); sys.exit(1)
        sys.exit(0)
    if a and a[0] == '--file':
        for line in open(a[1], encoding='utf8'):
            if line.strip():
                g, r = check(line)
                print('OK  ' if g else 'ERR ', line.strip(), '' if g else f'  <- {r["code"]}: {r["msg"]}')
    else:
        strict = '--strict' in a
        g, r = check(' '.join(x for x in a if x != '--strict'), strict)
        print(json.dumps(r, indent=1, ensure_ascii=False))
        sys.exit(0 if g else 1)